import {
  createBrowserHistory,
  createMemoryHistory,
  createRouterSelector,
  MemoryRouter,
  Redirect,
  Router,
  RouterActions,
  RouterSubscriber,
  usePathParam,
  useQueryParam,
  useRouter,
  useRouterActions,
  withRouter,
  RouteComponent,
  Link,
  createLegacyHistory,
  createRouterContext,
  findRouterContext,
  generatePath,
  matchRoute,
  invokePluginLoad,
  RouterStore,
  useRouterStoreActions,
  getRouterState,
  DEFAULT_MATCH,
  DEFAULT_ROUTE,
  createResource,
  ResourceDependencyError,
  ResourceSubscriber,
  useResource,
  useResourceStoreContext,
} from '../index';

describe('public API exports', () => {
  it.each([
    ['createBrowserHistory', createBrowserHistory],
    ['createMemoryHistory', createMemoryHistory],
    ['createRouterSelector', createRouterSelector],
    ['MemoryRouter', MemoryRouter],
    ['Redirect', Redirect],
    ['Router', Router],
    ['RouterActions', RouterActions],
    ['RouterSubscriber', RouterSubscriber],
    ['usePathParam', usePathParam],
    ['useQueryParam', useQueryParam],
    ['useRouter', useRouter],
    ['useRouterActions', useRouterActions],
    ['withRouter', withRouter],
    ['RouteComponent', RouteComponent],
    ['Link', Link],
    ['createLegacyHistory', createLegacyHistory],
    ['createRouterContext', createRouterContext],
    ['findRouterContext', findRouterContext],
    ['generatePath', generatePath],
    ['matchRoute', matchRoute],
    ['invokePluginLoad', invokePluginLoad],
    ['RouterStore', RouterStore],
    ['useRouterStoreActions', useRouterStoreActions],
    ['getRouterState', getRouterState],
    ['DEFAULT_MATCH', DEFAULT_MATCH],
    ['DEFAULT_ROUTE', DEFAULT_ROUTE],
    ['createResource', createResource],
    ['ResourceDependencyError', ResourceDependencyError],
    ['ResourceSubscriber', ResourceSubscriber],
    ['useResource', useResource],
    ['useResourceStoreContext', useResourceStoreContext],
  ])('%s is exported and defined', (_name, exportedValue) => {
    expect(exportedValue).toBeDefined();
  });
});
